// Generates public/sitemap.xml AND dist/sitemap.xml from scripts/routes.ts.
// Runs as part of `npm run build`, between vite build and prerender.
//
// Public copy is overwritten so that the source-of-truth lives in routes.ts,
// not a hand-edited XML file. Both `public/` (source) and `dist/` (built)
// copies are written so that dev preview and production stay in sync.

import { writeFile, mkdir } from 'node:fs/promises'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'
import { getSitemapEntries, ROOT, BASE_URL, type SitemapEntry } from './routes.ts'

function escapeXml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

export function renderEntry({
  url,
  priority,
  alternates,
  xDefault,
  changefreq,
}: SitemapEntry): string {
  const lines = []
  lines.push('  <url>')
  lines.push(`    <loc>${escapeXml(url)}</loc>`)
  if (alternates) {
    for (const { lang, url: altUrl } of alternates) {
      lines.push(
        `    <xhtml:link rel="alternate" hreflang="${lang}" href="${escapeXml(altUrl)}" />`
      )
    }
    lines.push(
      `    <xhtml:link rel="alternate" hreflang="x-default" href="${escapeXml(xDefault)}" />`
    )
  }
  if (changefreq) lines.push(`    <changefreq>${changefreq}</changefreq>`)
  lines.push(`    <priority>${priority.toFixed(1)}</priority>`)
  lines.push('  </url>')
  return lines.join('\n')
}

export function renderSitemapXml(entries: SitemapEntry[]): string {
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
    '        xmlns:xhtml="http://www.w3.org/1999/xhtml">',
    '',
    `  <!-- Generated by scripts/generate-sitemap.ts from ${BASE_URL} -->`,
    '',
    entries.map(renderEntry).join('\n'),
    '',
    '</urlset>',
    '',
  ].join('\n')
}

export async function main() {
  const entries = await getSitemapEntries()
  const xml = renderSitemapXml(entries)

  const publicPath = join(ROOT, 'public', 'sitemap.xml')
  const distPath = join(ROOT, 'dist', 'sitemap.xml')

  await writeFile(publicPath, xml, 'utf8')
  try {
    await mkdir(join(ROOT, 'dist'), { recursive: true })
    await writeFile(distPath, xml, 'utf8')
  } catch {
    // dist may not exist yet (running before vite build); public copy is enough
  }

  console.log(`Sitemap: ${entries.length} URLs`)
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((err: unknown) => {
    console.error(err)
    process.exit(1)
  })
}
